using KanchimeshAPI.Data;
using KanchimeshAPI.DTOs;
using KanchimeshAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KanchimeshAPI.Controllers;

[Route("api/settings/company")]
public sealed class CompanySettingsController(KanchimeshDbContext database) : ApiControllerBase
{
    /// <summary>
    /// Returns the business identity used on invoices. Before the first save,
    /// the API returns an empty profile so clients can render an editable
    /// settings form without special-case error handling.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(CompanyProfileDto), StatusCodes.Status200OK)]
    public async Task<ActionResult<CompanyProfileDto>> GetCompanyProfile(CancellationToken cancellationToken)
    {
        var profile = await database.CompanyProfiles
            .AsNoTracking()
            .SingleOrDefaultAsync(item => item.Id == CompanyProfile.DefaultId, cancellationToken);
        return Ok(ToDto(profile));
    }

    /// <summary>
    /// Updates the shared business identity and payment instructions shown on
    /// every invoice. Values are deliberately stored centrally rather than on
    /// a device so invoices generated by any signed-in client stay consistent.
    /// </summary>
    [HttpPut]
    [ProducesResponseType(typeof(CompanyProfileDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<CompanyProfileDto>> UpdateCompanyProfile(
        CompanyProfileRequest request,
        CancellationToken cancellationToken)
    {
        var profile = await database.CompanyProfiles
            .SingleOrDefaultAsync(item => item.Id == CompanyProfile.DefaultId, cancellationToken);
        if (profile is null)
        {
            profile = new CompanyProfile { Id = CompanyProfile.DefaultId };
            database.CompanyProfiles.Add(profile);
        }

        profile.CompanyName = NullIfWhiteSpace(request.CompanyName);
        profile.Address = NullIfWhiteSpace(request.Address);
        profile.City = NullIfWhiteSpace(request.City);
        profile.District = NullIfWhiteSpace(request.District);
        profile.State = NullIfWhiteSpace(request.State);
        profile.PostalCode = NullIfWhiteSpace(request.PostalCode);
        profile.Phone = NullIfWhiteSpace(request.Phone);
        profile.Email = NullIfWhiteSpace(request.Email);
        profile.GstNumber = NullIfWhiteSpace(request.GstNumber)?.ToUpperInvariant();
        profile.BankName = NullIfWhiteSpace(request.BankName);
        profile.BankAccountName = NullIfWhiteSpace(request.BankAccountName);
        profile.BankAccountNumber = NullIfWhiteSpace(request.BankAccountNumber);
        profile.BankIfscCode = NullIfWhiteSpace(request.BankIfscCode)?.ToUpperInvariant();
        profile.BankBranch = NullIfWhiteSpace(request.BankBranch);
        profile.UpiId = NullIfWhiteSpace(request.UpiId);

        await database.SaveChangesAsync(cancellationToken);
        return Ok(ToDto(profile));
    }

    public static CompanyProfileDto ToDto(CompanyProfile? profile) => new(
        profile?.CompanyName,
        profile?.Address,
        profile?.City,
        profile?.District,
        profile?.State,
        profile?.PostalCode,
        profile?.Phone,
        profile?.Email,
        profile?.GstNumber,
        profile?.BankName,
        profile?.BankAccountName,
        profile?.BankAccountNumber,
        profile?.BankIfscCode,
        profile?.BankBranch,
        profile?.UpiId,
        profile?.UpdatedAtUtc);
}
